fix: Set descriptions of all module options
This will otherwise causes build issues during `nixos-rebuild`:

    error: option services.sentinelone.dataDir has no description
    error: option services.sentinelone.email has no description
    error: option services.sentinelone.sentinelOneManagementTokenPath has no description
    error: option services.sentinelone.serialNumber has no description